function densityPlot(PSI, x, t, tIntr, xIntr, handle)

    axes(handle);
    
    surf(x(1:xIntr:end), t(1:tIntr:end), PSI(1:tIntr:end, 1:xIntr:end), 'EdgeColor', 'none'); 
    colormap('Jet');
    colorbar('eastoutside') 
    ylabel('t'); xlabel('x'); zlabel('|\psi|^2'); 
    view([0 0 90]) 

    hXLabel = xlabel('x');
    hYLabel = ylabel('t');

    pk_max = max(max(PSI));
    pk_min = min(min(PSI));
    caxis([pk_min pk_max]);
    
    set( gca                       , ...
        'FontName'   , 'Helvetica' );
    set([hXLabel, hYLabel         ], ...
        'FontName'   , 'Helvetica');
    set([hXLabel, hYLabel       ]  , ...
        'FontSize'   , 10          );

    set(gca, ...
      'Box'         , 'off'           , ...
      'TickDir'     , 'out'           , ...
      'TickLength'  , [.02 .02]       , ...
      'XMinorTick'  , 'off'           , ...
      'YMinorTick'  , 'off'           , ...
      'XGrid'       , 'off'           , ...
      'YGrid'       , 'off'           , ...
      'XColor'      , [.3 .3 .3]      , ...
      'YColor'      , [.3 .3 .3]      , ...
      'LineWidth'   , 1               , ...
      'XLim'        , [min(x) max(x)] ,...
      'YLim'        , [floor(min(t)) ceil(max(t))]);
  
%       disp('To save in high quality use this command');
%       disp('print -depsc2 -painters test3.eps');
end