function densityPlot(PSI, x, t, dt, dx, intr, selectAxes)

    axes(selectAxes);
    
    surf(x(1:1:end), t(1:intr:end), abs(PSI(1:intr:end, 1:1:end)).^2, 'EdgeColor', 'none'); 
    ylim([0, max(t)+dt]) 
    xlim([x(1) x(end)]) 
    colorbar('eastoutside') 
    ylabel('t'); xlabel('x'); zlabel('|\psi|^2'); 
    view([0 0 90]) 

    hXLabel = xlabel('x');
    hYLabel = ylabel('t');

    set( gca                       , ...
        'FontName'   , 'Helvetica' );
    set([hXLabel, hYLabel         ], ...
        'FontName'   , 'Helvetica');
    set([hXLabel, hYLabel       ]  , ...
        'FontSize'   , 10          );

    set(gca, ...
      'Box'         , 'off'        , ...
      'TickDir'     , 'out'        , ...
      'TickLength'  , [.02 .02]    , ...
      'XMinorTick'  , 'off'         , ...
      'YMinorTick'  , 'off'        , ...
      'XGrid'       , 'off'        , ...
      'YGrid'       , 'off'        , ...
      'XColor'      , [.3 .3 .3]   , ...
      'YColor'      , [.3 .3 .3]   , ...
      'LineWidth'   , 1            , ...
      'XLim'        , [0 max(t)+dt], ...
      'XLim'        , [min(x) max(x)+dx]);
  
      disp('To save in high quality use this command');
      disp('print -depsc2 -painters test3.eps');
end