function initialPlot(psi, x, selectAxes)

    axes(selectAxes)
    
    %plot(x, abs(psi).^2, 'LineWidth', 1.5); 
    %hold all;
    plot(x, real(psi), 'LineWidth', 1.5); 
    %hold all;
    %plot(x, imag(psi), 'LineWidth', 1.5); 
    

    hXLabel = xlabel('x');
    hYLabel = ylabel('\psi');

    set(gca                       , ...
        'FontName'   , 'Helvetica' );
    set([hXLabel, hYLabel         ], ...
        'FontName'   , 'Helvetica');
    set([hXLabel, hYLabel       ]  , ...
        'FontSize'   , 10          );

    set(gca, ...
      'Box'         , 'off'        , ...
      'TickDir'     , 'out'        , ...
      'TickLength'  , [.02 .02]    , ...
      'XMinorTick'  , 'off'         , ...
      'YMinorTick'  , 'off'        , ...
      'XGrid'       , 'on'        , ...
      'YGrid'       , 'on'        , ...
      'XColor'      , [.3 .3 .3]   , ...
      'YColor'      , [.3 .3 .3]   , ...
      'LineWidth'   , 1            , ...
      'XLim'        , [min(x) max(x)]);
  
  %legend('|\psi||', '\psi_r', '\psi_i', 'Location', 'Best');
end