function initialPlot(psi, x, handles)

    axes(handles.axes1)
    
    plot(x, abs(psi).^2); 

    hXLabel = xlabel('x');
    hYLabel = ylabel('|\psi|^2');

    set( gca                       , ...
        'FontName'   , 'Helvetica' );
    set([hXLabel, hYLabel         ], ...
        'FontName'   , 'Helvetica');
    set([hXLabel, hYLabel       ]  , ...
        'FontSize'   , 10          );

    set(gca, ...
      'Box'         , 'off'        , ...
      'TickDir'     , 'out'        , ...
      'TickLength'  , [.02 .02]    , ...
      'XMinorTick'  , 'off'         , ...
      'YMinorTick'  , 'off'        , ...
      'XGrid'       , 'on'        , ...
      'YGrid'       , 'on'        , ...
      'XColor'      , [.3 .3 .3]   , ...
      'YColor'      , [.3 .3 .3]   , ...
      'LineWidth'   , 1            , ...
      'XLim'        , [min(x) max(x)]);
end