function fig_hdl = maximaDisplay(PSI,x,t)
% MAXIMADISPLAY_BUILD
%-------------------------------------------------------------------------------
% File name   : maximaDisplay_build.m         
% Generated on: 30-Jan-2017 21:31:42          
% Description :
%-------------------------------------------------------------------------------


% Initialize handles structure
handles = struct();

% Create all UI controls
build_gui();

% Assign function output
fig_hdl = handles.maxima_GUI;
suprema = maxima(PSI, x, t);

lim = str2double(handles.minPeakEdit.String);
k = size(suprema); k = k(1);

I = suprema(:, 3) < lim;
suprema(I, :) = [];

handles.peaksTable.Data = suprema;

%% ---------------------------------------------------------------------------
	function build_gui()
% Creation of all uicontrols

		% --- FIGURE -------------------------------------
		handles.maxima_GUI = figure( ...
			'Tag', 'maxima_GUI', ...
			'Units', 'normalized', ...
			'Position', [0.5 0.5 0.149 0.3], ...
			'Name', 'Peak Finder', ...
			'MenuBar', 'none', ...
			'NumberTitle', 'off', ...
			'Color', get(0,'DefaultUicontrolBackgroundColor'));

		% --- STATIC TEXTS -------------------------------------
		handles.minPeakLabel = uicontrol( ...
			'Parent', handles.maxima_GUI, ...
			'Tag', 'minPeakLabel', ...
			'Style', 'text', ...
			'Units', 'normalized', ...
			'Position', [0.05 0.865 0.4 0.074], ...
			'FontSize', 10, ...
            'HorizontalAlignment', 'left', ...
			'String', 'Min. Peak Size');

		% --- EDIT TEXTS -------------------------------------
		handles.minPeakEdit = uicontrol( ...
			'Parent', handles.maxima_GUI, ...
			'Tag', 'minPeakEdit', ...
			'Style', 'edit', ...
			'Units', 'normalized', ...
			'Position', [0.55 0.88 0.4 0.074], ...
			'BackgroundColor', [1 1 1], ...
			'String', '0.3', ...
			'Callback', @minPeakEdit_Callback);

		% --- UITABLE -------------------------------------
		handles.peaksTable = uitable( ...
			'Parent', handles.maxima_GUI, ...
			'Tag', 'peaksTable', ...
			'UserData', zeros(1,0), ...
			'Units', 'normalized', ...
			'Position', [0.05 0.1 0.9 0.7], ...
			'BackgroundColor', [1 1 1;0.94 0.94 0.94], ...
			'ColumnEditable', [false,false,false], ...
			'ColumnFormat', {'char' 'char' 'char' }, ...
			'ColumnName', {'t','x','I'}, ...
			'ColumnWidth', {'auto','auto','auto'}, ...
			'Data', {'','','';'','','';'','','';'','',''});
	end

%% ---------------------------------------------------------------------------
	function minPeakEdit_Callback(hObject,evendata) %#ok<INUSD>;

    lim = str2double(hObject.String);
    k = size(suprema); k = k(1);

    I = suprema(:, 3) < lim;
    suprema(I, :) = [];

    handles.peaksTable.Data = suprema;
    
    end

end
