function fig_hdl = preferences
% Initialize handles structure
handles = struct();

% Create all UI controls
build_gui();

% Assign function output
fig_hdl = handles.prefGUI;

%% ---- LOAD HISTORY-------------------------------------------------------
if exist('pref.mat', 'file') == 2
    load('pref.mat', 'pref');
else
    createDefaultPref();
    load('pref.mat', 'pref');
end
handles.NxEdit.String = num2str(pref.Nx);
handles.NtEdit.String = num2str(pref.Nt);

if strcmp(pref.Lmode, 'manual');
    handles.LManualRadio.Value = 1;
    LManualRadio_Callback(handles.LManualRadio);
    handles.LEdit.String = num2str(pref.L);
else
    handles.LPeriodicRadio.Value = 1;
    LPeriodicRadio_Callback(handles.LPeriodicRadio);
    handles.aLMultEdit.String = num2str(pref.aLMult);
end

if strcmp(pref.plotType, '3D');
    handles.plot3DRadio.Value = 1;
else
    handles.plotDensityRadio.Value = 1;
end

if pref.pwr == 1;
    handles.z1Radio.Value = 1;
else
    handles.z1Radio.Value = 0;
end

if strcmp(pref.fourierPlotType, 'lines');
    handles.invLinesRadio.Value = 1;
else
    handles.invDensityRadio.Value = 1;
end
handles.invLinesEdit.String = num2str(pref.fourierLines);

%% ---- UI CONTROL CREATION -----------------------------------------------
function build_gui()

    %% --- FIGURE ----------------------------------------------
    handles.prefGUI = figure( ...
        'Tag', 'prefGUI', ...
        'Units', 'normalized', ...
        'Position', [0.43 0.16 0.31 0.46], ...
        'Name', 'Untitled', ...
        'MenuBar', 'none', ...
        'NumberTitle', 'off', ...
        'Color', get(0,'DefaultUicontrolBackgroundColor'));

    %% --- EXPORT PANEL ----------------------------------------
    handles.exportOptPanel = uipanel( ...
        'Parent', handles.prefGUI, ...
        'Tag', 'exportOptPanel', ...
        'UserData', zeros(1,0), ...
        'Units', 'normalized', ...
        'Position', [0.57 0.54 0.34 0.17], ...
        'Title', 'Export Options', ...
        'ShadowColor', [0.7 0.7 0.7]);
    % =========================================
    handles.decEdit = uicontrol( ...
        'Parent', handles.exportOptPanel, ...
        'Tag', 'decEdit', ...
        'UserData', zeros(1,0), ...
        'Style', 'edit', ...
        'Units', 'normalized', ...
        'Position', [0.59 0.24 0.35 0.42], ...
        'BackgroundColor', [1 1 1], ...
        'String', '5');
    handles.decLabel = uicontrol( ...
        'Parent', handles.exportOptPanel, ...
        'Tag', 'decLabel', ...
        'UserData', zeros(1,0), ...
        'Style', 'text', ...
        'Units', 'characters', ...
        'Position', [1.8 1.2 18 1.8], ...
        'String', 'Decimal Places');
    % =========================================

    %% --- DT PANEL --------------------------------------------
    handles.dtOptPanel = uibuttongroup( ...
        'Parent', handles.prefGUI, ...
        'Tag', 'dtOptPanel', ...
        'UserData', zeros(1,0), ...
        'Units', 'normalized', ...
        'Position', [0.083 0.2 0.45 0.51], ...
        'Title', 'DT Options');

    %% --- L GROUP ---------------------------------------------
    handles.lGroup = uibuttongroup( ...
        'Parent', handles.dtOptPanel, ...
        'Tag', 'lGroup', ...
        'UserData', zeros(1,0), ...
        'Units', 'normalized', ...
        'Position', [0.046 0.49 0.91 0.48], ...
        'Title', 'L');
    % =========================================
    handles.LPeriodicRadio = uicontrol( ...
        'Parent', handles.lGroup, ...
        'Tag', 'LPeriodicRadio', ...
        'UserData', zeros(1,0), ...
        'Style', 'radiobutton', ...
        'Units', 'normalized', ...
        'Position', [0.033 0.12 0.54 0.42], ...
        'FontSize', 9, ...
        'String', 'Periodic Multiple:', ...
        'Callback', @LPeriodicRadio_Callback);
    handles.LManualRadio = uicontrol( ...
        'Parent', handles.lGroup, ...
        'Tag', 'LManualRadio', ...
        'UserData', zeros(1,0), ...
        'Style', 'radiobutton', ...
        'Units', 'normalized', ...
        'Position', [0.033 0.5 0.42 0.42], ...
        'FontSize', 9, ...
        'String', 'Manual', ...
        'Callback', @LManualRadio_Callback);
            handles.aLMultEdit = uicontrol( ...
        'Parent', handles.lGroup, ...
        'Tag', 'aLMultEdit', ...
        'UserData', zeros(1,0), ...
        'Style', 'edit', ...
        'Units', 'normalized', ...
        'Position', [0.65 0.18 0.29 0.28], ...
        'BackgroundColor', [1 1 1], ...
        'String', '1');
    handles.LEdit = uicontrol( ...
        'Parent', handles.lGroup, ...
        'Tag', 'LEdit', ...
        'UserData', zeros(1,0), ...
        'Style', 'edit', ...
        'Units', 'normalized', ...
        'Position', [0.65 0.57 0.29 0.28], ...
        'BackgroundColor', [1 1 1], ...
        'String', '20', ...
        'Enable', 'off');
    % =========================================

    %% --- DT GRID GROUP ---------------------------------------
    handles.gridGroup = uibuttongroup( ...
        'Parent', handles.dtOptPanel, ...
        'Tag', 'gridGroup', ...
        'UserData', zeros(1,0), ...
        'Units', 'normalized', ...
        'Position', [0.048 0.07 0.91 0.39], ...
        'Title', 'Grid Size');
    % =========================================
    handles.NxLabel_lx = uicontrol( ...
        'Parent', handles.gridGroup, ...
        'Tag', 'NxLabel_lx', ...
        'UserData', zeros(1,0), ...
        'Style', 'text', ...
        'Units', 'normalized', ...
        'Position', [0.072 0.55 0.42 0.28], ...
        'FontSize', 9, ...
        'String', '$N_x$', ...
        'HorizontalAlignment', 'left');
    handles.NxEdit = uicontrol( ...
        'Parent', handles.gridGroup, ...
        'Tag', 'NxEdit', ...
        'UserData', zeros(1,0), ...
        'Style', 'edit', ...
        'Units', 'normalized', ...
        'Position', [0.65 0.55 0.29 0.36], ...
        'BackgroundColor', [1 1 1], ...
        'String', '256');
    handles.NtLabel_lx = uicontrol( ...
        'Parent', handles.gridGroup, ...
        'Tag', 'NtLabel_lx', ...
        'UserData', zeros(1,0), ...
        'Style', 'text', ...
        'Units', 'normalized', ...
        'Position', [0.073 0.21 0.42 0.21], ...
        'FontSize', 9, ...
        'String', '$N_t$', ...
        'HorizontalAlignment', 'left');
    handles.NtEdit = uicontrol( ...
        'Parent', handles.gridGroup, ...
        'Tag', 'NtEdit', ...
        'UserData', zeros(1,0), ...
        'Style', 'edit', ...
        'Units', 'normalized', ...
        'Position', [0.65 0.1 0.29 0.36], ...
        'BackgroundColor', [1 1 1], ...
        'String', '300');
    % =========================================
    handles.gridAxis = axes('parent',handles.gridGroup,'units','normalized','position',[0 0.12 1 1],'visible','off');
    % Find all static text UICONTROLS whose 'Tag' ends with '_lx'
    lbls = findobj(handles.gridGroup,'-regexp','tag','_lx*');
    for i=1:length(lbls)
        l = lbls(i);
        % Get current text, position and tag
        set(l,'units','normalized');
        s = get(l,'string');
        v = get(l, 'visible');
        p = get(l,'position');
        t = get(l,'tag');
        % Remove the UICONTROL
        delete(l);
        % Replace it with a TEXT object 
        handles.(t) = text(p(1),p(2),s,'interpreter','latex', 'visible', v);
    end

    %% --- PLOT TYPE GROUP ------------------------------------ 
    handles.plotTypeGroup = uibuttongroup( ...
        'Parent', handles.prefGUI, ...
        'Tag', 'plotTypeGroup', ...
        'Units', 'normalized', ...
        'Position', [0.083 0.75 0.22 0.19], ...
        'Title', 'Default Plot Type');
    % =========================================
    handles.plotDensityRadio = uicontrol( ...
        'Parent', handles.plotTypeGroup, ...
        'Tag', 'plotDensityRadio', ...
        'Style', 'radiobutton', ...
        'Units', 'normalized', ...
        'Position', [0.092 0.19 0.7 0.27], ...
        'String', 'Density Plot');
    handles.plot3DRadio = uicontrol( ...
        'Parent', handles.plotTypeGroup, ...
        'Tag', 'plot3DRadio', ...
        'Style', 'radiobutton', ...
        'Units', 'normalized', ...
        'Position', [0.092 0.49 0.7 0.27], ...
        'String', '3D');
    % =========================================

    %% --- Z-AXIS TYPE GROUP ---------------------------------- 
    handles.zTypePanel = uibuttongroup( ...
        'Parent', handles.prefGUI, ...
        'Tag', 'zTypePanel', ...
        'Units', 'normalized', ...
        'Position', [0.33 0.74 0.2 0.2], ...
        'Title', 'Z-Axis');
    % =========================================
    handles.z2Radio = uicontrol( ...
        'Parent', handles.zTypePanel, ...
        'Tag', 'z2Radio', ...
        'Style', 'radiobutton', ...
        'Units', 'normalized', ...
        'Position', [0.096 0.17 0.54 0.26], ...
        'String', '|psi|^2');
    handles.z1Radio = uicontrol( ...
        'Parent', handles.zTypePanel, ...
        'Tag', 'z1Radio', ...
        'Style', 'radiobutton', ...
        'Units', 'normalized', ...
        'Position', [0.096 0.47 0.53 0.26], ...
        'String', '|psi|');
    % =========================================

    %% --- INV TYPE GROUP ------------------------------------- 
    handles.invGroup = uibuttongroup( ...
        'Parent', handles.prefGUI, ...
        'Tag', 'invGroup', ...
        'Units', 'normalized', ...
        'Position', [0.57 0.75 0.34 0.19], ...
        'Title', 'Inverse Space Plot');
    % =========================================
    handles.invDensityRadio = uicontrol( ...
        'Parent', handles.invGroup, ...
        'Tag', 'invDensityRadio', ...
        'Style', 'radiobutton', ...
        'Units', 'normalized', ...
        'Position', [0.054 0.5 0.44 0.28], ...
        'String', 'Density', ...
        'Callback', @invDensityRadio_Callback);
    handles.invLinesRadio = uicontrol( ...
        'Parent', handles.invGroup, ...
        'Tag', 'invLinesRadio', ...
        'Style', 'radiobutton', ...
        'Units', 'normalized', ...
        'Position', [0.061 0.14 0.43 0.28], ...
        'String', 'Lines', ...
        'Callback', @invLinesRadio_Callback);
    handles.invLinesEdit = uicontrol( ...
        'Parent', handles.invGroup, ...
        'Tag', 'invLinesEdit', ...
        'Style', 'edit', ...
        'Units', 'normalized', ...
        'Position', [0.56 0.13 0.35 0.36], ...
        'BackgroundColor', [1 1 1], ...
        'String', '7');
    % =========================================

    %% --- BUTTONS -------------------------------------------- 
    handles.resetButton = uicontrol( ...
        'Parent', handles.prefGUI, ...
        'Tag', 'resetButton', ...
        'Style', 'pushbutton', ...
        'Units', 'normalized', ...
        'Position', [0.15 0.052 0.15 0.1], ...
        'String', 'Reset Defaults', ...
        'Callback', @resetButton_Callback);
    handles.cancelButton = uicontrol( ...
        'Parent', handles.prefGUI, ...
        'Tag', 'cancelButton', ...
        'UserData', 'cancelButton', ...
        'Style', 'pushbutton', ...
        'Units', 'normalized', ...
        'Position', [0.71 0.052 0.15 0.1], ...
        'String', 'Cancel', ...
        'Callback', @cancelButton_Callback);
    handles.okButton = uicontrol( ...
        'Parent', handles.prefGUI, ...
        'Tag', 'okButton', ...
        'Style', 'pushbutton', ...
        'Units', 'normalized', ...
        'Position', [0.43 0.052 0.15 0.1], ...
        'String', 'OK', ...
        'Callback', @okButton_Callback);

end

%% ---- CALL BACKS --------------------------------------------------------
function resetButton_Callback(hObject,evendata) %#ok<INUSD>
button = questdlg('Are you sure you want to reset preferences to default?');
switch button
    case 'Yes'
        delete pref.mat;
        uiwait(warndlg('Preferences reset to default.'));
        delete(handles.prefGUI);
        uiwait(preferences);
end
end

function cancelButton_Callback(hObject,evendata) %#ok<INUSD>
delete(handles.prefGUI);
end

function okButton_Callback(hObject,evendata) %#ok<INUSD>
pref.Nx = eval(handles.NxEdit.String);
pref.Nt = eval(handles.NtEdit.String);
if handles.LManualRadio.Value == 1;
    pref.Lmode = 'manual';
else
    pref.Lmode = 'periodic';
end
if handles.z1Radio.Value == 1;
    pref.pwr = 1;
else
    pref.pwr = 2;
end
if handles.plot3DRadio.Value == 1;
    pref.plotType = '3D';
else
    pref.plotType = 'density';
end
if handles.invLinesRadio.Value == 1;
    pref.fourierPlotType = 'lines';
else
    pref.fourierPlotType = 'density';
end
pref.fourierLines = eval(handles.invLinesEdit.String);

pref.L = eval(handles.LEdit.String);
pref.aLMult = eval(handles.aLMultEdit.String);
pref.dec = eval(handles.decEdit.String);

save('pref.mat', 'pref');   

delete(handles.prefGUI);
end

function LPeriodicRadio_Callback(hObject,evendata) %#ok<INUSD>
set(handles.LEdit, 'Enable', 'off')
set(handles.aLMultEdit, 'Enable', 'on')
end

function LManualRadio_Callback(hObject,evendata) %#ok<INUSD>
set(handles.LEdit, 'Enable', 'on')
set(handles.aLMultEdit, 'Enable', 'off')
end

function invLinesRadio_Callback(hObject,evendata) %#ok<INUSD>
set(handles.decEdit, 'Enable', 'on')
end

function invDensityRadio_Callback(hObject,evendata) %#ok<INUSD>
set(handles.decEdit, 'Enable', 'off')
end

end
