function [lh, h] = shiny3D(PSI, x, t, tIntr, xIntr, handle)

    axes(handle);
    
    h = surf(x(1:xIntr:end), t(1:tIntr:end), PSI(1:tIntr:end, 1:xIntr:end), 'EdgeColor', 'none');
               ylim([6, 10]);
               xlim([-4, 4]);
               
    colorbar off;
    view(-62,42)
    shading interp
    lh = lightangle(-40,50);
    h.FaceLighting = 'gouraud';
    h.AmbientStrength = 0.3;
    h.DiffuseStrength = 0.8;
    h.SpecularStrength = 0.5;
    h.SpecularExponent = 3;
    h.BackFaceLighting = 'unlit';
    grid off;
    zlabel('|\psi|^2'); 

    hXLabel = xlabel('x');
    hYLabel = ylabel('t');
    hZLabel = zlabel('|\psi|^2');

    set( gca                       , ...
        'FontName'   , 'Helvetica' );
    set([hXLabel, hYLabel, hZLabel         ], ...
        'FontName'   , 'Helvetica');
    set([hXLabel, hYLabel, hZLabel       ]  , ...
        'FontSize'   , 10          );

    set(gca, ...
      'Box'         , 'off'           , ...
      'TickDir'     , 'out'           , ...
      'TickLength'  , [.02 .02]       , ...
      'XMinorTick'  , 'off'           , ...
      'YMinorTick'  , 'off'           , ...
      'XGrid'       , 'off'           , ...
      'YGrid'       , 'off'           , ...
      'XColor'      , [.3 .3 .3]      , ...
      'YColor'      , [.3 .3 .3]      , ...
      'LineWidth'   , 1               );%, ...
      %'XLim'        , [min(x) max(x)] );%, ...
      %'YLim'        , [ceil(min(t)) ceil(max(t))] );
       % 'YLim'        , [ceil(min(t)) ceil(max(t))], ...
       grid off;
%       disp('To save in high quality use this command');
%       disp('print -depsc2 -painters test3.eps');
end